export const SKINS = [
  {
    id: 'default',
    name: 'Cube',
    description: 'Le cube classique',
    rarity: 'common',
    cost: 0,
    shape: 'square',
    color: 0x4fffb0,
    trailColor: 0x4fffb0,
    glowColor: 0x4fffb0,
    owned: true,
  },
  {
    id: 'fire',
    name: 'Flamme',
    description: 'Cube embrasé',
    rarity: 'common',
    cost: 50,
    shape: 'square',
    color: 0xff6b35,
    trailColor: 0xff4500,
    glowColor: 0xff6b35,
    owned: false,
  },
  {
    id: 'ice',
    name: 'Glace',
    description: 'Cube cristallin',
    rarity: 'common',
    cost: 50,
    shape: 'square',
    color: 0x74b9ff,
    trailColor: 0x0984e3,
    glowColor: 0x74b9ff,
    owned: false,
  },
  {
    id: 'ball',
    name: 'Sphère',
    description: 'Forme ronde',
    rarity: 'rare',
    cost: 150,
    shape: 'circle',
    color: 0xa29bfe,
    trailColor: 0x6c5ce7,
    glowColor: 0xa29bfe,
    owned: false,
  },
  {
    id: 'neon',
    name: 'Néon',
    description: 'Pur néon lumineux',
    rarity: 'rare',
    cost: 200,
    shape: 'square',
    color: 0x00ff87,
    trailColor: 0x00ff87,
    glowColor: 0x00ff87,
    owned: false,
  },
  {
    id: 'gold',
    name: 'Or',
    description: 'Cube doré brillant',
    rarity: 'rare',
    cost: 250,
    shape: 'square',
    color: 0xffd700,
    trailColor: 0xffaa00,
    glowColor: 0xffd700,
    owned: false,
  },
  {
    id: 'glitch',
    name: 'Glitch',
    description: 'Cube glitché',
    rarity: 'epic',
    cost: 500,
    shape: 'square',
    color: 0xff00ff,
    trailColor: 0x00ffff,
    glowColor: 0xff00ff,
    owned: false,
  },
  {
    id: 'diamond',
    name: 'Diamant',
    description: 'Le plus rare des cubes',
    rarity: 'epic',
    cost: 750,
    shape: 'diamond',
    color: 0x81ecec,
    trailColor: 0x00cec9,
    glowColor: 0x81ecec,
    owned: false,
  },
  {
    id: 'void',
    name: 'Vide',
    description: 'Absorbe la lumière',
    rarity: 'epic',
    cost: 900,
    shape: 'circle',
    color: 0x2d3436,
    trailColor: 0x6c5ce7,
    glowColor: 0x6c5ce7,
    owned: false,
  },
];

export const RARITY_COLORS = {
  common: 0xb2bec3,
  rare: 0x70a1ff,
  epic: 0xeccc68,
};

export const RARITY_LABELS = {
  common: 'COMMUN',
  rare: 'RARE',
  epic: 'ÉPIQUE',
};
